# Introduction {#intro}

More than half of the global population lives in urban areas with this proportion expected to increase to two-thirds by 2050 [@UnitedNations2019]. As the population size of an urban area increases so does the land area it occupies, a process known as urbanization [@UnitedNations2019]. Urbanization is accompanied by a suite of surface modifications that affect the surface-energy balance, hydrological flows, and the abundance of vegetation [@Pickett2001]. These modifications affect the climate system by creating distinct and varied microclimates [@Pickett2001]. Urbanization produces a spatially variable physical environmental with uneven landscapes of environmental externalities and benefits, and infrastructure access. The spatial variation in the urban environment in turn affect and are affected by community demographics, frequently with distinct inequalities across socio-economic lines [@Heynan2006; @Wolch2014; @geeEnvironmentalHealthDisparities2004]. Systematic inequalities arise from discriminatory zoning practices and civic disinvestment, both of which have long historical legacies [@Wolch2014; @williamsSocialDeterminantsTaking2009; @hoffmanEffectsHistoricalHousing2020; @geeEnvironmentalHealthDisparities2004]. 

These three subsystems–climatic, environmental, and social–are highly interdependent and interact in complex ways characterized by non-linear dynamics, complex feedbacks, and thresholding behaviors, operating across a variety of spatial and temporal scales [@Liu2007; @Liu2007a; @McPhearson2016; @Pickett2001; @costanzaModelingComplexEcological1993a]. Although the distinctions between these systems are fuzzy, it is helpful to define the climate system as encompassing the measurable characteristics of the surface-energy balance including land surface temperature (LST), precipitation and weather, atmospheric gases, and particulate matter. The environmental system comprises qualities of the physical environment including land cover, fractional vegetation, zoning and land use, building characteristics, and transportation networks. The social system we define as the intersectional characteristics of individuals, neighborhoods, and communities like poverty, health-care coverage, and the socially-defined concepts of race and ethnicity. These climatic, environmental, and social components should be examined simultaneously in relation to each other to improve our understanding of urban systems as a whole rather than the sum of their parts [@Pickett2001].

Human beings affect and are affected by all three of these systems and their interactions [@Ferraro2019; @Liu2007; @Liu2007a; @Pickett2001] and climate change coupled with increasing urban populations is projected to alter them further [@ebiClimateChangeTropospheric2008]. While urbanization is generally seen as a positive force for human development and poverty reduction, unmanaged urbanization has the potential for environmental degradation and inequitable sharing of beneficial outcomes [@UnitedNations2019]. Understanding how these systems currently interact is imperative to understanding how to best manage urbanization in order to minimize functional disruption and increase equity [@McPhearson2016]. 

Public health is defined as the health of entire populations and is best understood as a complex system with multiple agents including citizens, governments, and non-governmental organizations [@Trochim2006]. As the world becomes increasingly urban, understanding the dynamics of public health in urban environments and how they are affected by climate, the environment, and society becomes increasingly important [@Bai2018].  Knowledge of the structural and spatial variability of public health across these domains can support better public policies and resource allocation [@McPhearson2016; @jiaTop10Research2019]. Sustainable cities require health equity [@UnitedNations2019; @McPhearson2016]. 

Weather affects human health in both the long term and the short term. Everyday climatic conditions affect health in addition to disasters like floods, hurricanes, and tornadoes; extreme heat is the leading cause of weather-related death in the United States [@Luber2008]. Extremes of both heat and cold can exacerbate existing conditions, affect cardiovascular and respiratory function, and may lead to increased mortality [@ferreirabragaTimeCourseWeatherRelated2001; @sonejaExposureExtremeHeat2016]. Humidity increases the apparent temperature, exacerbating these effects [@linExtremeHighTemperatures2009]. Heat facilitates the formation of ground-level O$_3$ which is known to adversely affect respiratory function [@ebiClimateChangeTropospheric2008] and climatic factors influence the concentration of air pollutants [@damatoEnvironmentalRiskFactors2005]. Precipitation and wind affect the severity of allergen concentrations [@sonejaExposureExtremeHeat2016]. Health effects may occur at a temporal lag from these climatic conditions [@Liu2007a; @Liu2007] with some findings pointing toward changes in conditions rather than the absolute values of the climatic variables having a greater effect [@mirekuChangesWeatherEffects2009]. Climatic conditions affect public health differentially across socio-economic groups [@Liu2007a]. Studies have suggested a variety of factors including increased vulnerability due to the psycho-social stress of discrimination, poor access to health care, lack of air conditioning units in homes, lack of vegetation, poor housing quality, and proximity to pollution sources [@Heaton2014; @Vargo2016; @baileyStructuralRacismHealth2017; @marteniesDiseaseHealthInequalities2017].

The physical environment varies spatially within urban areas producing variabilities in health based on proximity to features of the built environment [@srinivasanCreatingHealthyCommunities2003; @chenSpatiotemporalRelationshipParticle2007]. There is evidence that residential proximity to point source pollution is associated with long-term respiratory effects [@buteauReviewEffectAir2019] and proximity to high traffic areas with asthma-related hospitalizations [@wilhelmEnvironmentalPublicHealth2008; @chenSpatiotemporalRelationshipParticle2007; @liAsthmaExacerbationProximity2011]. Reduced lung function in children is associated with concentrations of particulate matter (PM) [@jamesAssociationImprovedAir2015] and proximity to railyards [@spencer-hwangRespiratoryHealthRisks2015]. Urban core areas are affected by the urban heat island (UHI) effect where the increased percentage of impervious surfaces and decreased amount of greenspace elevate land surface temperature (LST) [@okeEnergeticBasisUrban1982; @wesleyGreenspacePatternSurface2019]. Not only do age and condition of housing directly impact the health of residents [@baileyStructuralRacismHealth2017], building and street dimensions, permeability, and building materials impact microclimates by modifying the surface-energy balance [@stewartLocalClimateZones2012; @chingWUDAPTUrbanWeather2018].

It is extensively documented that large disparities in health outcomes exist across socio-economic spectra, with minorities and the poor having the worst outcomes [@geeEnvironmentalHealthDisparities2004; @samuels-kalowUseGeographicData2019; @baileyStructuralRacismHealth2017]. These social determinants of health vary spatially along with the physical and environmental determinants of health through residential segregation and structural racism [@geeEnvironmentalHealthDisparities2004; @hoffmanEffectsHistoricalHousing2020; @baileyStructuralRacismHealth2017]. Environmental exposure along with the associated health risks is unevenly distributed and communities of color are frequently subject to civic disinvestment and lack of economic and political opportunities [@schulzRACEDISTRIBUTIONSOCIAL2016; @baileyStructuralRacismHealth2017]. Consequently, there is often a surfeit of dilapidated housing stock and reduced access to quality education and healthcare [@baileyStructuralRacismHealth2017].

A specific example of a health outcome driven by climatic, environmental, and social factors is asthma. Asthma is a chronic inflammation of the airways characterized by recurrent episodes of wheezing, coughing, shortness of breath, and tightness of chest associated with airflow obstruction [@fordConsiderationsRegardingEpidemiology2010; @Won2016]. It is not a disease but rather a diverse disorder that affects both children and adults although with somewhat different presentations [@trivediAsthmaChildrenAdults2019]. It is the most common chronic condition of childhood in developed nations [@milliganAsthmaUrbanChildren2016]. In the United States pediatric asthma is associated with 50 billion dollars in healthcare expenditures annually and causes significant disruptions to both children and parents due to absenteeism [@trivediAsthmaChildrenAdults2019]. Pediatric asthma doubled in the United States between 1980 and 1995 and although overall growth has slowed since then, racial disparities have increased [@akinbamiChangingTrendsAsthma2016]. Minority and low-income children are disproportionately affected in terms of prevalence rates, morbidity, and mortality [@trivediAsthmaChildrenAdults2019; @Won2016]. 

Pediatric asthma prevalence is associated with a host of demographic and environmental exposure factors [@fordConsiderationsRegardingEpidemiology2010] making an attractive case study to analyze the complex interactions of climatic, environmental, and social systems. Asthma has been shown to be associated with temperature, humidity, thunderstorms, allergens, air pollution, greenspace, proximity to transportation corridors, minority status, and poverty among other factors [@sonejaExposureExtremeHeat2016; @mirekuChangesWeatherEffects2009; @raunUsingCommunityLevel2014; @trivediAsthmaChildrenAdults2019; @Won2016; @liAsthmaExacerbationProximity2011].

Studying the interactions of urban systems and their relationship with public health requires both an outcome and an instance. The proposed research seeks to explore and describe pediatric asthma in the Kansas City metropolitan area as an example of the variability of public health. This research is guided by the question: how does public health relate to the interactions of climatic conditions, environmental characteristics, and social factors and their spatial and temporal variability? 





















