# Current research and limitations {#limits}

Asthma has been variously shown to be effected by air pressure, temperature, thunderstorms, allergens, and air pollution [@Won2016; @sonejaExposureExtremeHeat2016]. @Ayres-Sampaio2014 found that hospital admission rates due to asthma were positively related to $NO_2$ and air temperature and negatively related to NDVI. However, they examined relationships in linear regressions for each variable separately. Air temperature, $NO_2$, NDVI, and additionally relative humidity and $PM_{10}$ are not independent of each other with the authors even stating the NDVI and $NO_2$ were highly correlated in every season. Additionally, the variables included were seasonal averages per municipality and outside of NDVI and the hospitalization rates, the variables were derived from modeling including Kriging for the relative humidity, land-use regression for $NO_2$ and $PM_{10}$, and calculating the air temperature from a DEM, MODIS temperature profiles, and air pressure from meterological stations. Not only does this increase dependence among the independent variables because many are calculated based on the others, any error in these calculations would compound in the linear regressions with hospitalization rate.

@babinPediatricPatientAsthmarelated2007 They examined the emergency room visitation and admissions rates per zip code; even the authors admit that aggregating to the zip code level likely obscures inhomogeneity that is statistically important.  The rates were calculated after removing long-term seasonal trends with a natural cubic spline with 12 knots. They found strong and significant relationships between pediatric asthma and ozone and weed pollen, especially among children ages 5-12. They also found a strong logarithmic relationship between both emergency room (ER) visits and emergency room admissions and the percent of households living below the poverty line. Like @Ayres-Sampaio2014, it seems as though they considered the relationships between the independent variables and the emergency room rate separately without controlling for the other variables which include: $O_3$; $PM2.5$; daily maximum temperature; tree, grass, and weed pollen; and mold, although the methods are not clear. Although they examined ER visit rate variation across poverty levels, they did this separately from the atmospheric and environmental analysis. 

[@brewerDoesNeighborhoodSocial2017] examine the relationship between social and environmental context and pediatric asthma rates. They use a cross-classified multi-level logistic regression analysis to account for the fact that children are both nested within neighborhoods (census tracts) and cross classified within clinics and to assess the variance contributed by each. The dependent variable was a binary prediction of child diagnosis. They used the first dimension of a principal components analysis based on census tract characteristics to develop a measure of concentrated disadvantage. Other independent variables include: $O_3$ and $PM2.5$ both calculated as quarterly means, individual-level demographic characteristics, and the percent of neighborhood residents that share the individual's race/ethnicity. They found that concentrated disadvantage increased asthma and that the coethnic percentage increased the odds of asthma diagnosis for Black and asian children but not white or Hispanic. These disparities were evident even after accounting for both individual and neighborhood characteristics. They found no effect for $O_3$ and $PM2.5$. Although the authors did an excellent job of designing their research, they admit that increased measures of air pollution would better describe the relationship between air quality and asthma incidence. They speculate that Houston's poor air quality overall may be responsible for the lack of relationship, which may indicate the need for a third level of hierachy representing the city overall. Additionally, the long-term averages of $O_3$ and $PM2.5$ obscure any relationship between air pollution and acute asthmatic episodes. They also acknowledge the possibility that multivariate regression can obscure the spatial variability of environmental indicators.

While there are many studies of the relationship between health outcomes in relation to urban heat, heat waves, and other atmospheric conditions like air pollution levels, the public health data are often too aggregated to get a sense of the spatial dependency of these relationships [@Anderson2009; @Ayres-Sampaio2014; @babinPediatricPatientAsthmarelated2007; @delamaterAnalysisAsthmaHospitalizations2012; @ferreirabragaTimeCourseWeatherRelated2001; @mirekuChangesWeatherEffects2009; @sonejaExposureExtremeHeat2016]. Patterns of these variables vary spatially [@okeEnergeticBasisUrban1982; @Jerrett2008super] in ways that affect exposure and health outcomes [@jiaTop10Research2019; @sonejaExposureExtremeHeat2016; @williamsSocialDeterminantsTaking2009]. These patterns are obscured when working at too coarse a spatial resolution. Additionally, many of these studies do not ask how these relationships may vary by social factors like ethnicity or poverty [@Ayres-Sampaio2014; @delamaterAnalysisAsthmaHospitalizations2012] although many studies show that they do [@linExtremeHighTemperatures2009]. 

Likewise, while many studies research the relationship between health outcomes and the built and physical environment, most are focused on the benefits of greenspace or the negatives of busy transportation corridors [@villeneuveCohortStudyRelating2012b]. While these may highlight the differential effects of these relationships across social groups, they often do so without simultaneously considering the relationship between the built and physical environment and the urban atmosphere [citation?]. It has been well established that increased impervious surfaces and the lack of greenspace in urban areas contribute to the urban heat island effect (UHI) where temperatures are higher in urban areas relative to surrounding rural areas [@okeEnergeticBasisUrban1982]. It has also been shown that areas that were subject to redlining have increased temperatures relative to areas that were greenlined [@hoffmanEffectsHistoricalHousing2020]. Research also shows that there are significant income and racial disparities in access to public greenspace [@abercrombieIncomeRacialDisparities2008]. Increased heat has significant negative effects on health [@Horton2016]. So how to disentangle these factors? Although it seems to be the privelage of a discipline to decide which variables to consider mediating, moderating, or confounding, this avoids the need to characterize urban systems not as partitions of relationships but as complex, hierarchical, and coupled.

Relationships between health and the urban atmosphere need to be considered not only at the system level (county or metro area) or community level (zip code or census block group) but also at the individual level. 





@babinPediatricPatientAsthmarelated2007 found a positive relationship between $O_3$ and pediatric asthma but their dataset spanned only three years and was aggregated to the zip code level.

## Urban infrastructure and environment {#urbenv-pubhealth}

@villeneuveCohortStudyRelating2012b found that there was an inverse relationship between greenspace and mortality. Urban trees contribute to improved air quality by reducing air pollution concentrations [@nowakAirPollutionRemoval2006]. 

## Social determinants of health {#soc-det}

@babinPediatricPatientAsthmarelated2007 found a logarithmic relationship between pediatric asthma-related emergency departmnet visits and the percentage of children living below the poverty level but this data was aggregated to the zip code level.


# Limitations of simple modeling techniques {#model-limits}


* Missing data---cloud cover, etc.
* Trying to combine qualitative and quantitative data types.
* Spatial and temporal granularity
  * (census tracts dividing the city; days, weeks, months, years) 
  * levels of detail
  * poor localization
* collinearity

These issues are interesting as well as problematic.














##### Quotes

Public health requires transdisciplinary approaches to modelling the complex systems that interact to produce variabilities in outcomes [@Trochim2006].

"Future multi-level studies considering individuals nested within neighborhoods would limit false ecological inferences" [@Uejio2011]

"A research approach that focuses on the relationship of individual risk factors related to asthma is unlikely to capture the complex and multidimensional factors that contribute to the variation in asthma prevalence and morbidity. Research is needed that incorporates a life course, cumulative risk perspective and that seeks to integrate how multiple risks and resources linked to the individual, family, housing, neighborhood, and societal level relate to each other and combine to affect childhood asthma." [@williamsSocialDeterminantsTaking2009]


"Environmental processes arise from interactions of various processes. These interactions are often occurring at various scales in space and time. Although it is often convenient to simplify such systems either by ignoring the multivariate interaction, or by assuming spatial/temporal stationarity, linearity, and Gaussianity, it is increasingly the case that the scientific questions of interest are becoming sufficiently complex that one can no longer justify such assumptions." [@wikleHierarchicalModelsEnvironmental2003]. "these data are often of differing spatial and temporal support, orientation, and alignment, relative to the process of interest" [@wikleHierarchicalModelsEnvironmental2003] "the environment encompasses many different interacting processes. It follows that one of the biggest challenges and growth areas in environmental statistics will be concerned with linking the many processes contributing to specific environmental questions of concern" [@wikleHierarchicalModelsEnvironmental2003].

"THere are varying intervals of time between human-nature interactions and their ecological and socioeconomic effects." [@Liu2007a]

"Studying CHANs requires a new paradigm that emphasizes hierarchical couplings of natural and human sysems across organizational, spatial, and temporal scales." [@Liu2007a]

"It is important to note that there was no expectation of high correlations with the environmental variables because the exacerbation of asthma symptoms depends on several other external factors (e.g., indoor pollution, viral infections) and host factors (e.g., genetics)" [@Ayres-Sampaio2014]



