# Bayesian hierarchical modeling {#model}

If there are three qualities of models that cannot all be maximized---realism, precision, and generality [@costanzaModelingComplexEcological1993a]---our aim is to maximize realism and generality. And if increasing resolution to accurately describe the underlying processes means decreasing predictability [@costanzaModelingComplexEcological1993a], our goal is to explore and describe an urban system comprised of climatic, social, and environmental subsystems that interact in complex ways, moving towards a universal methodology. This is largely uncharted territory, both technically and pragmatically, but a better understanding of the interactions between these systems has the potential to increase environmental justice and decrease health disparities. 

A zero-inflated Poisson process is appropriate for modeling pediatric asthma occurrence. Poisson distributions describe the probability of discrete events occurring in fixed intervals of time when the probability of events occurring at time $t$ are independent of events occurring at time $t-1$. Zero-inflated models are mixture models that account for an excess of zeros by assuming that the zero counts may be attributable to either a process where the probability of a zero count is 1, or a separate count process [@statrethinkingbook]. In this case, zero counts may be the consequence of the fact that only approximately 7.5\% of children have asthma (https://www.cdc.gov/nchs/fastats/asthma.htm) and among children who do have asthma, asthma symptoms do not always result in a visit to a medical facility. The overall probabilities for the zero-inflated Poisson are expressed as follows:
```{r include=F, eval = F}
#https://math.usu.edu/jrstevens/biostat/projects2013/rep_ZIP.pdf
```

\begin{equation}
P(Y_i=y_i|x_i,z_i)=
\begin{cases}
\psi_i+(1-\psi_i)e^{-\lambda_i} & \text{if } y_i=0,  \text{ zero-count process}\\
(1-\psi_i)\frac{e^{-\lambda_i}\lambda_i^{y_i}}{y_i!} & \text{if } y_i > 0, \text{Poisson process} \\
\end{cases}
(\#eq:poisson)
\end{equation}

\noindent where $\lambda_i$ is the conditional mean count per space-time interval (time period and census tract), otherwise known as the rate parameter, and $\psi_i$ is the probability that observation $i$ is characterized by the zero-count process, written as: 

\begin{equation}
\psi_i=F(z_i'\gamma) 
(\#eq:zero-count)
\end{equation}

\noindent where $z_i$ is a vector of covariates and $\gamma$ is the vector of coefficients of a logit or probit model [@statrethinkingbook]. 
Regardless of whether the raw counts are used or if they are standardized by calculating the effective asthma rate per spatial area per day, the dependent variable is still the result of a Poisson process. Although the rate will not be an integer value it will still be discrete and therefore appropriate to be modelled with a Poisson distribution.

Many researchers acknowledge the necessity of a hierarchical approach to modeling public health data [@brewerDoesNeighborhoodSocial2017; @Liu2007a; @Uejio2011; @williamsSocialDeterminantsTaking2009; @bestComparisonBayesianSpatial2005]. Individuals are nested within neighborhoods which are nested within urban areas. Each level of the hierarchy interacts with higher and lower levels in systematic ways, where the higher levels act as constraints and the lower levels represent noise [@costanzaModelingComplexEcological1993a]. Failure to model the non-linear variability in the lower levels can lead to significant aggregation error [@costanzaModelingComplexEcological1993a]. Furthermore, hierarchical models simplify complicated systems by separating joint distributions of covariates into separate conditional models which are linked by probability rules with uncertainty quantified at every level [@wikleHierarchicalModelsEnvironmental2003]. 

When analyzing a phenomena in both space and time it is important to note that there may be different spatial effects at different points in time and different temporal effects in different locations in space [@wikleHierarchicalBayesianSpacetime1998]. Bayesian spatio-temporal models implemented in a hierarchical framework permit the incorporation of space-time interactions at different levels in the hierarchical structure as well as allowing high dimensionality [@wikleHierarchicalBayesianSpacetime1998]. In particular, Bayesian spatio-temporal models account for spatial autocorrelation in the data with spatial random effects, time-dependency with temporal effects, the uncertainty attributable to measured confounders with time-varying covariates, and the additional variation unaccounted for by the random effects with space-time interaction effects [@Khana2018]. 

Bayesian methods make explicit use of probability distributions to quantify inferential uncertainty and incorporate expert knowledge through the specification of prior distributions for the estimated parameters [@lynchIntroductionAppliedBayesian2007]. These priors are then conditioned on the observed data resulting in posterior estimates of the parameter distributions. These distributions represent intervals with a high probability of containing the quantity of interest, an advantage over the frequentist paradigm that interprets confidence intervals only in relation to a repeated series of similar trials [@gelmanBayesianDataAnalysis2013]. 

The foundation of Bayesian inference is Baye's theorem:

\begin{equation}
\underbrace{p(\theta|data)}_\text{posterior}\propto\underbrace{p(data|\theta)}_\text{likelihood}\times\underbrace{p(\theta)}_\text{prior}
(\#eq:bayes)
\end{equation}

\noindent which states that the probability of a parameter given the data is proportional to the probability of the data conditioned on the parameter multiplied by the marginal probability for the parameter. In other words, the posterior distribution is the the prior distribution weighted by the observed data. 

Consider there are $G$ groups of observations

\begin{equation}
y_{ig}\sim{Q(\theta_g)}
(\#eq:groups)
\end{equation}

\noindent where $Q$ is the distribution of the observations within the groups each having its own parameter $\theta_g$ 

\begin{equation}
\theta_g\sim{W(\gamma)}
(\#eq:group-param)
\end{equation}

\noindent and $W$ is the  distribution of the group parameters $\theta_g$ defined by parameter $\gamma$. $\gamma$ is called the hyperparameter and also has its own distribution. Combined, the posterior distribution for all the unknown parameters is:

\begin{equation}
p(\gamma, \theta|y) \propto p(y|\theta, \gamma)p(\theta|\gamma)p(\gamma)
(\#eq:posterior)
\end{equation}

\noindent where $p(\theta|\gamma)p(\gamma)$ is the marginal joint distribution for the parameter and the hyperparameter. The posterior distribution for the hyperparameter $\gamma$ that governs the group-level parameters is given by its marginal distribution:

\begin{equation}
p(\gamma|y) \propto \int p(y|\theta, \gamma)p(\theta|\gamma)p(\gamma)d\theta
(\#eq:post-hyper)
\end{equation}

\noindent where the integration is accomplished stochastically through Markov chain Monte Carlo (MCMC) sampling from the conditional posterior distributions of the parameters [@lynchIntroductionAppliedBayesian2007].

An advantage of a Bayesian MCMC approach over maximum likelihood methods is that the group-level parameters are estimated in the model rather than considering them as part of the error term. This measures the uncertainty of the random effects and permits exploring their structure [@burknerBrmsPackageBayesian2017; @miaouRoadwayTrafficCrash2003]. A hierarchical Bayesian model allows the modeling of spatial random effects, i.e. differences in the relationship between the covariates and pediatric asthma incidence across census tracts. Additionally, due to the low observational count per individual census tract on any given day, there is a large variability between analysis units that can make simple estimates unreliable. The high geographical and temporal resolution produces data that is sparse by nature, posing statistical problems of observational noise corrupting the signal of interest [@bestComparisonBayesianSpatial2005]. Hierarchical Bayesian models with spatial random effects can account for this high variance and reveal geographic patterns in the data [@miaouRoadwayTrafficCrash2003]. These models utilize information from surrounding areas, thus borrowing strength in order to produce smoothed estimates for the individual census tracts, preserving geographic resolution while producing stable estimates [@ghoshHierarchicalBayesGLMs1999; @bestComparisonBayesianSpatial2005; @Khana2018]. The individual parameter values of the tracts shrink towards a value defined by the distribution of all of the tracts in the hierarchical structure [@bestComparisonBayesianSpatial2005]. Additionally, the structured heterogeneity of spatial correlation between neighboring census tracts can be specified [@ghoshHierarchicalBayesGLMs1999]. 

The successful model can be parsed in many ways, with the model results indicating the key processes that lead to variation in pediatric asthma. Even if the framework is not successful, the failure can guide other attempts. Regardless, the methodology should provide enough information to prioritize variables in subsequent models whether they are general and conceptual or instantiated and precise. Constructing a modeling framework that incorporates climatic, environmental, and social systems at several spatial and temporal scales may provide a methodology applicable to much more than pediatric asthma in the Kansas City metro area. Moving forward, the pursuit is of an understanding of how the urban system emerges from the interactions of its constituent subsystems.

# Methods {#methods}

The primary objective of this research is to construct a statistically robust model that integrates climatic, environmental, and social systems. To accomplish this, every step must be thoroughly considered and made with informed intent. Designing the architecture of the model will be both challenging and time intensive, and model specification will be contingent upon extensive research into the specifics of Bayesian hierarchical models and the structures of the component subsystems. This modeling framework will inform our understanding of the dominant covariance structures and collinearities in the urban system that give rise to variations in pediatric asthma. 

The first step in the proposed research will be to construct a database of the desired variables (See Section \@ref(data)) for the duration of the available asthma data. Presumably, all data will be aggregated to the census tract level per day. Processing of the remotely sensed data will be done using Google Earth Engine with all other variables being processed using the R language for statistical computing [@rcoreteamLanguageEnvironmentStatistical2020]. The dimensionality of the variable space may be quite high, in which case, reduction techniques such as PCA may be explored as necessary. For instance, @brewerDoesNeighborhoodSocial2017 used PCA to construct a concentrated disadvantage index from a combination of socioeconomic variables. 

The next step will be a thorough review of the relevant literature. One of the key requirements in Bayesian analysis is the assignment of prior distributions for the estimated parameters and while it is always possible to assign an uninformative prior with a diffuse distribution, if there is substantive knowledge the parameters can be constrained into finite regions, improving model estimation [@gelmanBayesianDataAnalysis2013]. If there are known mechanistic relationships between variables, this would guide the specification of priors. Additionally, all variables and their relationships with asthma counts as well as the other covariates will be explored descriptively. The hierarchy of the data and groups within each level need to be specified and understanding the structure of the data is crucial. 

Model checking and sensitivity analysis will be conducted after the posterior distributions of the parameters and hyperparamters are estimated in order to improve the model. We anticipate that several models will be constructed both for comparison of the selected variables and structured hierarchies, and through iterative improvement of the successful model/s. 

It will hopefully be apparent which variables are the key factors that govern the interactions of climate, environment, and society within the urban system. These variables, in addition to any non-intuitive findings, will be explored in depth to investigate the dominant processes that contribute to the variation of pediatric asthma. Understanding process mechanisms can potentially inform effective public health intervention.

A key difficulty and opportunity of this research will be the effective visualization of the high-dimensional structure of both the covariate space and the estimated parameter space. Novel ways of mapping how the parameters change in time and space will be an important contribution of this research. Possibilities include animations and interactive maps which could allow the exploration of how pediatric asthma variability might might be altered by changing conditions. Such visualizations are important for improving the understanding of the complex urban system, especially for non-scientists.

These potential analyses are highly dependent upon the success and structure of the coupled urban model. Just like the complex system to be modeled, the modeling proces and the subsequent analysis will be nonlinear processes replete with feedback cycles and surprises. Flexibility is paramount.















