# A tentative modeling approach {#model}

Hierarchical models connect a series of conditional models with probability rules and make it possible to account for uncertainties, use first principles, and simiplify modeling specifications [@wikleHierarchicalModelsEnvironmental2003]. Joint distributions of covariates can be separaated into a series of conditional models [@wikleHierarchicalModelsEnvironmental2003]. "as the level of complexity increases (or "subjective" prior information is included) the Bayesian paradigm is usually necessary" [@wikleHierarchicalModelsEnvironmental2003]. "hierarchical modeling provides a framework by which to simplify complicated environmental systems, so that uncertainty can be linked in a coherent fashion" [@wikleHierarchicalModelsEnvironmental2003].

An advantage of a Bayesian MCMC approach over maximum likelihood methods is that the group-level parameters are estimated in the model rather than considering them part of the error term. Not only does this provide measures of uncertainty of the random effects, it enables exploring the structure of the random effects  [@burknerBrmsPackageBayesian2017; @miaouRoadwayTrafficCrash2003]. A hierarchical Bayes model would allow the modeling of spatial random effects, i.e. differences in the relationship between the covariates and pediatric asthma incidence between census tracts. Assessing the spatial variability of risk can allow for prioritazation of resources to those communities most at risk. Additionally, due to the low count of incidence per individual census tract, there is a large variability between analysis units that can make simple estimates unreliable. Poisson-based hierarchical Bayes models with spatial random effects can account for this high variance and reveal geographic patterns in the data [@miaouRoadwayTrafficCrash2003]. These models utilize information from surrounding areas, thus borrowing strength in order to produce smoothed estimates for the individual census tracts, preserving geographic resolution while producing stable estimates [@ghoshHierarchicalBayesGLMs1999; @bestComparisonBayesianSpatial2005 ]. The point values shrink towards a value defined by the distribution of all of the tracts in the hierarchical structure [@bestComparisonBayesianSpatial2005]. Additionally, the structured heterogeneity of spatial correlation between neighboring census tracts can be specified [@ghoshHierarchicalBayesGLMs1999]. The small geographical and temporal resolution produces data that is sparse by nature, posing statistical problems of observational noise corrupting the signal of interest [@bestComparisonBayesianSpatial2005].
