# Significance {#signif}

Pediatric asthma offers an intriguing case study for modeling urban areas as coupled human-natural systems since it is associated with a host of demographic and environmental exposure factors [@fordConsiderationsRegardingEpidemiology2010]. Urban systems are comprised of meteorological, environmental, and social systems. Although there are many studies concerning the relationship between asthma---or other measures of public health---and these subsystems, they are primarily addressed independent of one another. However, these systems interact in complex ways and are highly interdependent, with each subsystem and their interactions operating at a multitude of spatial and temporal scales [@Liu2007; @Liu2007a; @McPhearson2016; @Pickett2001; @costanzaModelingComplexEcological1993a]. In order to understand the coupling of these subsystems they must be considered simultaneously with an emphasis on spatial and temporal hierarchies [@Liu2007a; @Liu2007]. Much of the work that has been done with coupled human-natural systems has been theoretical rather than empirical [@Liu2007]. However, as a nascent field, empirical and inductive research has much to offer in terms of understanding general relationships and structures. 

The study of urban systems is usually siloed within separate disciplines [@Bai2018]. It is inefficient to study human and natural systems separately when attempting to understand their interactions [@Liu2007a]. Likewise, research is usually done in the abstract, without a focused eye to solving real-world problems. Research should provide usable solutions [@Liu2007a; @McPhearson2016]. Addressing these problems successfully involves transdisciplinary work that can examine urban systems as intersections of social, physical, environmental, and atmospheric systems [@Bai2018; @McPhearson2016]. Understanding urban systems is a critical first step in understanding how they may respond to climate change [@Bai2018] and how this may affect public health. If health risks can be understood quantitatively they can be projected under different climate change scenarios [@McMichael2012]. 

The long-standing paradigm for studying urban systems was to conceptualize them as human systems superimposed upon natural systems. It has become clear that a more accurate model is that of coupled and natural systems which explicitly characterize the multidirectional and dynamic interactions between these systems. The modeling of coupled and human natural systems requires statistical techniques that unite data across spatial and temporal scales and can derive meaning over many levels of uncertainty [@Liu2007a]. Improving these techniques will be key to predicting the effects of climate change on public health. 


